behaviors:
  Game2048:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024  # 增加批次大小
      buffer_size: 24576  # 增加缓冲区大小
      learning_rate: 1.5e-4  # 稍微降低学习率
      beta: 3.0e-3
      epsilon: 0.2
      lambd: 0.98  # 进一步增加 lambda
      num_epoch: 5  # 增加训练轮次
    network_settings:
      normalize: true
      hidden_units: 768  # 增加网络容量
      num_layers: 5  # 增加层数
    reward_signals:
      extrinsic:
        gamma: 0.997  # 进一步提高折扣因子
        strength: 1.0
      curiosity:
        strength: 0.005
        gamma: 0.997
        encoding_size: 384
    max_steps: 2.0e7  # 增加训练步数
    time_horizon: 512
    summary_freq: 50000
    threaded: true